name: live_house_nav
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  riverpod_generator: ^2.2.3
  go_router: ^8.0.1
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  google_maps_flutter: ^2.3.0
  freezed_annotation: ^2.2.0
  geolocator: ^8.2.1
  http: ^1.0.0
  google_fonts: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/jsons/google_map_style.json
    - assets/pngs/no_image.png