name: live_house_nav
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.5
  riverpod_generator: ^2.3.2
  go_router: ^10.1.2
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  google_maps_flutter: ^2.3.0
  freezed_annotation: ^2.4.1
  geolocator: ^8.2.1
  http: ^1.0.0
  google_fonts: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  firebase_core: ^2.16.0
  geoflutterfire_plus: ^0.0.14
  cloud_firestore: ^4.8.2
  rxdart: ^0.27.7
  json_annotation: ^4.8.1
  photo_view: ^0.14.0
  syncfusion_flutter_sliders: ^22.2.10
  firebase_auth: ^4.10.0
  image_picker: ^1.0.4
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  freezed: ^2.4.2
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/jsons/google_map_style.json
    - assets/facility/
    - .env
